version: '3.7'

services: 
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres
    environment: 
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: develop
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes: 
      - postgres-data:/var/lib/postgresql/data
volumes: 
  postgres-data: